name: simp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.15+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.2
  url_launcher: ^6.0.3
  splashscreen: ^1.3.5
  flutter_icons: ^1.1.0
  http: ^0.12.2
  shared_preferences: ^2.0.5
  video_player: ^1.0.1
  rounded_loading_button: ^1.0.18
  path_provider: ^2.0.1
  onesignal_flutter: ^2.6.3
  clipboard: ^0.1.2+8
  local_auth: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - imagens/ic_launcher.png
    - imagens/b2cor.png
    - imagens/bg.png
    - imagens/card.png
    - imagens/card-off.png
    - imagens/logo.png
    - imagens/bg-f.png
    - imagens/ag.png
    - imagens/s.mp4
    - imagens/bgcor.jpg
    - imagens/b2cor-gif.gif
    - imagens/2.gif